/**
 * AUTO-GENERATED by scripts/i18n-sync.mjs — 请勿手改！
 *
 * 共享词条生成物（单一来源：backend/i18n/langs/{zh-CN,en,ja}.ts + scripts/i18n-shared-manifest.json）。
 * 修改译文请改 backend 语言包；登记/调整共享映射请改 manifest，然后运行：
 *   node scripts/i18n-sync.mjs
 */

import backendEn from '../../../../../backend/i18n/langs/en';

const sharedEn = {
    app: {
        agentStopNotification: {
            actions: {
                continue: backendEn.notifications.windowsAgentStop.actionLabels.continue,
                executePlan: backendEn.notifications.windowsAgentStop.actionLabels.executePlan,
                generatePlan: backendEn.notifications.windowsAgentStop.actionLabels.generatePlan,
            },
        },
    },
    common: {
        completed: backendEn.tools.reviewDocument.values.milestoneStatus.completed,
        confirm: backendEn.notifications.windowsAgentStop.actionLabels.genericConfirmation,
        date: backendEn.tools.reviewDocument.header.date,
        description: backendEn.tools.reviewDocument.finding.description,
        error: backendEn.modules.mcp.status.error,
        failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
        hide: backendEn.tools.common.hide,
        resume: backendEn.notifications.windowsAgentStop.actionLabels.continue,
        show: backendEn.tools.common.show,
        status: backendEn.tools.reviewDocument.header.status,
        unknownError: backendEn.modules.api.chat.errors.unknownError,
    },
    components: {
        backgroundTasks: {
            completed: backendEn.tools.reviewDocument.values.milestoneStatus.completed,
            failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
        },
        channels: {
            anthropic: {
                thinking: {
                    displaySummarized: backendEn.tools.reviewDocument.milestone.summary,
                    effortLow: backendEn.tools.reviewDocument.values.severity.low,
                    effortMedium: backendEn.tools.reviewDocument.values.severity.medium,
                },
            },
            gemini: {
                thinking: {
                    levelHigh: backendEn.tools.reviewDocument.values.severity.high,
                    levelLow: backendEn.tools.reviewDocument.values.severity.low,
                    levelMedium: backendEn.tools.reviewDocument.values.severity.medium,
                },
            },
            openai: {
                thinking: {
                    effortHigh: backendEn.tools.reviewDocument.values.severity.high,
                    effortLow: backendEn.tools.reviewDocument.values.severity.low,
                    effortMedium: backendEn.tools.reviewDocument.values.severity.medium,
                },
            },
        },
        common: {
            confirmDialog: {
                confirm: backendEn.notifications.windowsAgentStop.actionLabels.genericConfirmation,
                title: backendEn.notifications.windowsAgentStop.actionLabels.genericConfirmation,
            },
        },
        input: {
            fileNotExists: backendEn.webview.errors.fileNotExists,
            notifications: {
                fileInOtherWorkspace: backendEn.webview.errors.fileInOtherWorkspace,
                fileNotInAnyWorkspace: backendEn.webview.errors.fileNotInAnyWorkspace,
            },
            promptContext: {
                readFailed: backendEn.webview.errors.readFileFailed,
            },
        },
        message: {
            checkpoint: {
                restoreResultFailed: backendEn.modules.checkpoint.errors.restoreFailed,
            },
            continue: {
                button: backendEn.notifications.windowsAgentStop.actionLabels.continue,
            },
            responseViewer: {
                status: backendEn.tools.reviewDocument.header.status,
                toolStatuses: {
                    error: backendEn.notifications.windowsAgentStop.reasonLabels.error,
                },
            },
            tool: {
                designCard: {
                    generatePlan: backendEn.notifications.windowsAgentStop.actionLabels.generatePlan,
                    openFileFailed: backendEn.webview.errors.openFileFailed,
                },
                error: backendEn.modules.mcp.status.error,
                openDiffFailed: backendEn.webview.errors.openDiffPreviewFailed,
                planCard: {
                    executePlan: backendEn.notifications.windowsAgentStop.actionLabels.executePlan,
                    openFileFailed: backendEn.webview.errors.openFileFailed,
                },
                progressCard: {
                    currentProgress: backendEn.tools.reviewDocument.summary.currentProgress,
                    issueError: backendEn.modules.mcp.status.error,
                    latestConclusion: backendEn.tools.reviewDocument.summary.latestConclusion,
                    milestoneStatusCompleted: backendEn.tools.reviewDocument.values.milestoneStatus.completed,
                    milestoneStatusInProgress: backendEn.tools.reviewDocument.values.milestoneStatus.inProgress,
                    status: backendEn.tools.reviewDocument.milestone.status,
                    statusActive: backendEn.tools.reviewDocument.values.milestoneStatus.inProgress,
                    statusCompleted: backendEn.tools.reviewDocument.values.milestoneStatus.completed,
                },
                reject: backendEn.tools.file.diffCodeLens.reject,
                rejectAll: backendEn.tools.file.diffCodeLens.rejectAll,
                reviewCard: {
                    categoryAccessibility: backendEn.tools.reviewDocument.values.category.accessibility,
                    categoryCss: backendEn.tools.reviewDocument.values.category.css,
                    categoryDocs: backendEn.tools.reviewDocument.values.category.docs,
                    categoryHtml: backendEn.tools.reviewDocument.values.category.html,
                    categoryJavascript: backendEn.tools.reviewDocument.values.category.javascript,
                    categoryMaintainability: backendEn.tools.reviewDocument.values.category.maintainability,
                    categoryOther: backendEn.tools.reviewDocument.values.category.other,
                    categoryPerformance: backendEn.tools.reviewDocument.values.category.performance,
                    categoryTest: backendEn.tools.reviewDocument.values.category.test,
                    changeDescription: backendEn.tools.reviewDocument.finding.description,
                    changeEvidence: backendEn.tools.reviewDocument.finding.evidenceFiles,
                    changeRecommendation: backendEn.tools.reviewDocument.finding.recommendation,
                    changeRelatedMilestoneIds: backendEn.tools.reviewDocument.finding.relatedMilestones,
                    changeSeverity: backendEn.tools.reviewDocument.finding.severity,
                    changeTrackingStatus: backendEn.tools.reviewDocument.finding.trackingStatus,
                    decision: backendEn.tools.reviewDocument.milestone.conclusion,
                    decisionAccepted: backendEn.tools.reviewDocument.values.overallDecision.accepted,
                    decisionConditionallyAccepted: backendEn.tools.reviewDocument.values.overallDecision.conditionallyAccepted,
                    decisionRejected: backendEn.tools.reviewDocument.values.overallDecision.rejected,
                    evidence: backendEn.tools.reviewDocument.milestone.evidenceFiles,
                    findings: backendEn.tools.reviewDocument.milestone.findings,
                    generatePlan: backendEn.notifications.windowsAgentStop.actionLabels.generatePlan,
                    issueError: backendEn.modules.mcp.status.error,
                    latestConclusion: backendEn.tools.reviewDocument.summary.latestConclusion,
                    modules: backendEn.tools.reviewDocument.summary.reviewedModules,
                    recommendedNextAction: backendEn.tools.reviewDocument.summary.recommendedNextAction,
                    severityHigh: backendEn.tools.reviewDocument.values.severity.high,
                    severityLow: backendEn.tools.reviewDocument.values.severity.low,
                    severityMedium: backendEn.tools.reviewDocument.values.severity.medium,
                    status: backendEn.tools.reviewDocument.header.status,
                    statusCompleted: backendEn.tools.reviewDocument.values.milestoneStatus.completed,
                    statusInProgress: backendEn.tools.reviewDocument.values.milestoneStatus.inProgress,
                    tracking: backendEn.tools.reviewDocument.finding.trackingStatus,
                    trackingAcceptedRisk: backendEn.tools.reviewDocument.values.trackingStatus.acceptedRisk,
                    trackingDuplicate: backendEn.tools.reviewDocument.values.trackingStatus.duplicate,
                    trackingFixed: backendEn.tools.reviewDocument.values.trackingStatus.fixed,
                    trackingOpen: backendEn.tools.reviewDocument.values.trackingStatus.open,
                    trackingWontFix: backendEn.tools.reviewDocument.values.trackingStatus.wontFix,
                },
                todoPanel: {
                    statusCompleted: backendEn.tools.reviewDocument.values.milestoneStatus.completed,
                    statusInProgress: backendEn.tools.reviewDocument.values.milestoneStatus.inProgress,
                },
            },
        },
        settings: {
            autoExec: {
                categories: {
                    other: backendEn.tools.reviewDocument.values.category.other,
                },
            },
            channelSettings: {
                dialog: {
                    delete: {
                        confirm: backendEn.notifications.windowsAgentStop.actionLabels.genericConfirmation,
                    },
                },
                form: {
                    multimodal: {
                        document: backendEn.tools.reviewDocument.values.category.docs,
                    },
                },
                selector: {
                    confirm: backendEn.notifications.windowsAgentStop.actionLabels.genericConfirmation,
                },
            },
            checkpoint: {
                sections: {
                    cleanup: {
                        manifestNote: backendEn.modules.checkpoint.restore.excludedNote,
                        phaseAfter: backendEn.modules.checkpoint.description.after,
                        phaseBefore: backendEn.modules.checkpoint.description.before,
                        progress: {
                            failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
                        },
                    },
                    tools: {
                        afterLabel: backendEn.modules.checkpoint.description.after,
                        beforeLabel: backendEn.modules.checkpoint.description.before,
                    },
                },
            },
            contextSettings: {
                diagnostics: {
                    severity: {
                        error: backendEn.modules.mcp.status.error,
                    },
                },
            },
            dependencySettings: {
                progress: {
                    installSuccess: backendEn.modules.dependencies.progress.installSuccess,
                    unknownError: backendEn.modules.api.chat.errors.unknownError,
                },
            },
            mcp: {
                connected: backendEn.modules.mcp.status.connected,
                disconnected: backendEn.modules.mcp.status.disconnected,
                error: backendEn.modules.mcp.status.error,
            },
            mcpSettings: {
                form: {
                    description: backendEn.tools.reviewDocument.finding.description,
                    serverIdError: backendEn.modules.mcp.errors.invalidServerId,
                },
                serverCard: {
                    connecting: backendEn.modules.mcp.status.connecting,
                },
                status: {
                    connected: backendEn.modules.mcp.status.connected,
                    connecting: backendEn.modules.mcp.status.connecting,
                },
            },
            modelManager: {
                errors: {
                    addFailed: backendEn.modules.api.models.errors.addModelsFailed,
                    editFailed: backendEn.modules.api.models.errors.updateModelFailed,
                    removeFailed: backendEn.modules.api.models.errors.removeModelFailed,
                    setActiveFailed: backendEn.modules.api.models.errors.setActiveModelFailed,
                },
            },
            promptSettings: {
                assemblyMode: {
                    description: backendEn.webview.promptSettings.assemblyMode.description,
                    entriesDescription: backendEn.webview.promptSettings.assemblyMode.entriesDescription,
                    entriesLabel: backendEn.webview.promptSettings.assemblyMode.entriesLabel,
                    legacyDescription: backendEn.webview.promptSettings.assemblyMode.legacyDescription,
                    legacyLabel: backendEn.webview.promptSettings.assemblyMode.legacyLabel,
                    title: backendEn.webview.promptSettings.assemblyMode.title,
                },
                dynamicSection: {
                    strategyDescription: backendEn.webview.promptSettings.dynamicSection.strategyDescription,
                    strategyPreserve: backendEn.webview.promptSettings.dynamicSection.strategyPreserve,
                    strategyPreserveWarning: backendEn.webview.promptSettings.dynamicSection.strategyPreserveWarning,
                    strategySingle: backendEn.webview.promptSettings.dynamicSection.strategySingle,
                    strategyTitle: backendEn.webview.promptSettings.dynamicSection.strategyTitle,
                    strategyVarsPrefix: backendEn.webview.promptSettings.dynamicSection.strategyVarsPrefix,
                    strategyVarsSeparator: backendEn.webview.promptSettings.dynamicSection.strategyVarsSeparator,
                    strategyVarsSuffix: backendEn.webview.promptSettings.dynamicSection.strategyVarsSuffix,
                    strategyVarsWarning: backendEn.webview.promptSettings.dynamicSection.strategyVarsWarning,
                },
            },
            subagents: {
                description: backendEn.tools.reviewDocument.finding.description,
            },
            toolSettings: {
                common: {
                    error: backendEn.modules.mcp.status.error,
                },
                files: {
                    applyDiff: {
                        diffGuardWarning: backendEn.tools.file.diffManager.diffGuardWarning,
                    },
                },
                terminal: {
                    executeCommand: {
                        execTimeout: backendEn.tools.errors.timeout,
                    },
                },
            },
            toolsSettings: {
                categories: {
                    other: backendEn.tools.reviewDocument.values.category.other,
                },
            },
        },
        subagents: {
            monitor: {
                resume: backendEn.notifications.windowsAgentStop.actionLabels.continue,
                status: {
                    completed: backendEn.tools.reviewDocument.values.milestoneStatus.completed,
                    failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
                },
            },
        },
        tools: {
            error: backendEn.modules.mcp.status.error,
            file: {
                createDirectoryPanel: {
                    failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
                },
                deleteFilePanel: {
                    failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
                },
            },
            media: {
                cropImagePanel: {
                    status: {
                        error: backendEn.modules.mcp.status.error,
                        failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
                generateImagePanel: {
                    status: {
                        error: backendEn.modules.mcp.status.error,
                        failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
                removeBackgroundPanel: {
                    status: {
                        error: backendEn.modules.mcp.status.error,
                        failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
                resizeImagePanel: {
                    status: {
                        error: backendEn.modules.mcp.status.error,
                        failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
                rotateImagePanel: {
                    status: {
                        error: backendEn.modules.mcp.status.error,
                        failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
            },
            reject: backendEn.tools.file.diffCodeLens.reject,
            subagents: {
                completed: backendEn.tools.reviewDocument.values.milestoneStatus.completed,
            },
            terminal: {
                executeCommandPanel: {
                    status: {
                        failed: backendEn.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
            },
        },
    },
    composables: {
        useAttachments: {
            errors: {
                readFileFailed: backendEn.webview.errors.readFileFailed,
            },
        },
    },
    errors: {
        cancelled: backendEn.errors.cancelled,
        unknown: backendEn.errors.unknown,
    },
    stores: {
        chatStore: {
            errors: {
                restoreCheckpointFailed: backendEn.modules.checkpoint.errors.restoreFailed,
                unknownError: backendEn.modules.api.chat.errors.unknownError,
            },
        },
        terminalStore: {
            errors: {
                killTerminalFailed: backendEn.webview.errors.killTerminalFailed,
            },
        },
    },
};

export default sharedEn;
