/**
 * AUTO-GENERATED by scripts/i18n-sync.mjs — 请勿手改！
 *
 * 共享词条生成物（单一来源：backend/i18n/langs/{zh-CN,en,ja}.ts + scripts/i18n-shared-manifest.json）。
 * 修改译文请改 backend 语言包；登记/调整共享映射请改 manifest，然后运行：
 *   node scripts/i18n-sync.mjs
 */

import backendJa from '../../../../../backend/i18n/langs/ja';

const sharedJa = {
    app: {
        agentStopNotification: {
            actions: {
                continue: backendJa.notifications.windowsAgentStop.actionLabels.continue,
                executePlan: backendJa.notifications.windowsAgentStop.actionLabels.executePlan,
                generatePlan: backendJa.notifications.windowsAgentStop.actionLabels.generatePlan,
            },
        },
    },
    common: {
        completed: backendJa.tools.reviewDocument.values.milestoneStatus.completed,
        confirm: backendJa.notifications.windowsAgentStop.actionLabels.genericConfirmation,
        date: backendJa.tools.reviewDocument.header.date,
        description: backendJa.tools.reviewDocument.finding.description,
        error: backendJa.modules.mcp.status.error,
        failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
        hide: backendJa.tools.common.hide,
        resume: backendJa.notifications.windowsAgentStop.actionLabels.continue,
        show: backendJa.tools.common.show,
        status: backendJa.tools.reviewDocument.header.status,
        unknownError: backendJa.modules.api.chat.errors.unknownError,
    },
    components: {
        backgroundTasks: {
            completed: backendJa.tools.reviewDocument.values.milestoneStatus.completed,
            failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
        },
        channels: {
            anthropic: {
                thinking: {
                    displaySummarized: backendJa.tools.reviewDocument.milestone.summary,
                    effortLow: backendJa.tools.reviewDocument.values.severity.low,
                    effortMedium: backendJa.tools.reviewDocument.values.severity.medium,
                },
            },
            gemini: {
                thinking: {
                    levelHigh: backendJa.tools.reviewDocument.values.severity.high,
                    levelLow: backendJa.tools.reviewDocument.values.severity.low,
                    levelMedium: backendJa.tools.reviewDocument.values.severity.medium,
                },
            },
            openai: {
                thinking: {
                    effortHigh: backendJa.tools.reviewDocument.values.severity.high,
                    effortLow: backendJa.tools.reviewDocument.values.severity.low,
                    effortMedium: backendJa.tools.reviewDocument.values.severity.medium,
                },
            },
        },
        common: {
            confirmDialog: {
                confirm: backendJa.notifications.windowsAgentStop.actionLabels.genericConfirmation,
                title: backendJa.notifications.windowsAgentStop.actionLabels.genericConfirmation,
            },
        },
        input: {
            fileNotExists: backendJa.webview.errors.fileNotExists,
            notifications: {
                fileInOtherWorkspace: backendJa.webview.errors.fileInOtherWorkspace,
                fileNotInAnyWorkspace: backendJa.webview.errors.fileNotInAnyWorkspace,
            },
            promptContext: {
                readFailed: backendJa.webview.errors.readFileFailed,
            },
        },
        message: {
            checkpoint: {
                restoreResultFailed: backendJa.modules.checkpoint.errors.restoreFailed,
            },
            continue: {
                button: backendJa.notifications.windowsAgentStop.actionLabels.continue,
            },
            responseViewer: {
                status: backendJa.tools.reviewDocument.header.status,
                toolStatuses: {
                    error: backendJa.notifications.windowsAgentStop.reasonLabels.error,
                },
            },
            tool: {
                designCard: {
                    generatePlan: backendJa.notifications.windowsAgentStop.actionLabels.generatePlan,
                    openFileFailed: backendJa.webview.errors.openFileFailed,
                },
                error: backendJa.modules.mcp.status.error,
                openDiffFailed: backendJa.webview.errors.openDiffPreviewFailed,
                planCard: {
                    executePlan: backendJa.notifications.windowsAgentStop.actionLabels.executePlan,
                    openFileFailed: backendJa.webview.errors.openFileFailed,
                },
                progressCard: {
                    currentProgress: backendJa.tools.reviewDocument.summary.currentProgress,
                    issueError: backendJa.modules.mcp.status.error,
                    latestConclusion: backendJa.tools.reviewDocument.summary.latestConclusion,
                    milestoneStatusCompleted: backendJa.tools.reviewDocument.values.milestoneStatus.completed,
                    milestoneStatusInProgress: backendJa.tools.reviewDocument.values.milestoneStatus.inProgress,
                    status: backendJa.tools.reviewDocument.milestone.status,
                    statusActive: backendJa.tools.reviewDocument.values.milestoneStatus.inProgress,
                    statusCompleted: backendJa.tools.reviewDocument.values.milestoneStatus.completed,
                },
                reject: backendJa.tools.file.diffCodeLens.reject,
                rejectAll: backendJa.tools.file.diffCodeLens.rejectAll,
                reviewCard: {
                    categoryAccessibility: backendJa.tools.reviewDocument.values.category.accessibility,
                    categoryCss: backendJa.tools.reviewDocument.values.category.css,
                    categoryDocs: backendJa.tools.reviewDocument.values.category.docs,
                    categoryHtml: backendJa.tools.reviewDocument.values.category.html,
                    categoryJavascript: backendJa.tools.reviewDocument.values.category.javascript,
                    categoryMaintainability: backendJa.tools.reviewDocument.values.category.maintainability,
                    categoryOther: backendJa.tools.reviewDocument.values.category.other,
                    categoryPerformance: backendJa.tools.reviewDocument.values.category.performance,
                    categoryTest: backendJa.tools.reviewDocument.values.category.test,
                    changeDescription: backendJa.tools.reviewDocument.finding.description,
                    changeEvidence: backendJa.tools.reviewDocument.finding.evidenceFiles,
                    changeRecommendation: backendJa.tools.reviewDocument.finding.recommendation,
                    changeRelatedMilestoneIds: backendJa.tools.reviewDocument.finding.relatedMilestones,
                    changeSeverity: backendJa.tools.reviewDocument.finding.severity,
                    changeTrackingStatus: backendJa.tools.reviewDocument.finding.trackingStatus,
                    decision: backendJa.tools.reviewDocument.milestone.conclusion,
                    decisionAccepted: backendJa.tools.reviewDocument.values.overallDecision.accepted,
                    decisionConditionallyAccepted: backendJa.tools.reviewDocument.values.overallDecision.conditionallyAccepted,
                    decisionRejected: backendJa.tools.reviewDocument.values.overallDecision.rejected,
                    evidence: backendJa.tools.reviewDocument.milestone.evidenceFiles,
                    findings: backendJa.tools.reviewDocument.milestone.findings,
                    generatePlan: backendJa.notifications.windowsAgentStop.actionLabels.generatePlan,
                    issueError: backendJa.modules.mcp.status.error,
                    latestConclusion: backendJa.tools.reviewDocument.summary.latestConclusion,
                    modules: backendJa.tools.reviewDocument.summary.reviewedModules,
                    recommendedNextAction: backendJa.tools.reviewDocument.summary.recommendedNextAction,
                    severityHigh: backendJa.tools.reviewDocument.values.severity.high,
                    severityLow: backendJa.tools.reviewDocument.values.severity.low,
                    severityMedium: backendJa.tools.reviewDocument.values.severity.medium,
                    status: backendJa.tools.reviewDocument.header.status,
                    statusCompleted: backendJa.tools.reviewDocument.values.milestoneStatus.completed,
                    statusInProgress: backendJa.tools.reviewDocument.values.milestoneStatus.inProgress,
                    tracking: backendJa.tools.reviewDocument.finding.trackingStatus,
                    trackingAcceptedRisk: backendJa.tools.reviewDocument.values.trackingStatus.acceptedRisk,
                    trackingDuplicate: backendJa.tools.reviewDocument.values.trackingStatus.duplicate,
                    trackingFixed: backendJa.tools.reviewDocument.values.trackingStatus.fixed,
                    trackingOpen: backendJa.tools.reviewDocument.values.trackingStatus.open,
                    trackingWontFix: backendJa.tools.reviewDocument.values.trackingStatus.wontFix,
                },
                todoPanel: {
                    statusCompleted: backendJa.tools.reviewDocument.values.milestoneStatus.completed,
                    statusInProgress: backendJa.tools.reviewDocument.values.milestoneStatus.inProgress,
                },
            },
        },
        settings: {
            autoExec: {
                categories: {
                    other: backendJa.tools.reviewDocument.values.category.other,
                },
            },
            channelSettings: {
                dialog: {
                    delete: {
                        confirm: backendJa.notifications.windowsAgentStop.actionLabels.genericConfirmation,
                    },
                },
                form: {
                    multimodal: {
                        document: backendJa.tools.reviewDocument.values.category.docs,
                    },
                },
                selector: {
                    confirm: backendJa.notifications.windowsAgentStop.actionLabels.genericConfirmation,
                },
            },
            checkpoint: {
                sections: {
                    cleanup: {
                        manifestNote: backendJa.modules.checkpoint.restore.excludedNote,
                        phaseAfter: backendJa.modules.checkpoint.description.after,
                        phaseBefore: backendJa.modules.checkpoint.description.before,
                        progress: {
                            failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
                        },
                    },
                    tools: {
                        afterLabel: backendJa.modules.checkpoint.description.after,
                        beforeLabel: backendJa.modules.checkpoint.description.before,
                    },
                },
            },
            contextSettings: {
                diagnostics: {
                    severity: {
                        error: backendJa.modules.mcp.status.error,
                    },
                },
            },
            dependencySettings: {
                progress: {
                    installSuccess: backendJa.modules.dependencies.progress.installSuccess,
                    unknownError: backendJa.modules.api.chat.errors.unknownError,
                },
            },
            mcp: {
                connected: backendJa.modules.mcp.status.connected,
                disconnected: backendJa.modules.mcp.status.disconnected,
                error: backendJa.modules.mcp.status.error,
            },
            mcpSettings: {
                form: {
                    description: backendJa.tools.reviewDocument.finding.description,
                    serverIdError: backendJa.modules.mcp.errors.invalidServerId,
                },
                serverCard: {
                    connecting: backendJa.modules.mcp.status.connecting,
                },
                status: {
                    connected: backendJa.modules.mcp.status.connected,
                    connecting: backendJa.modules.mcp.status.connecting,
                },
            },
            modelManager: {
                errors: {
                    addFailed: backendJa.modules.api.models.errors.addModelsFailed,
                    removeFailed: backendJa.modules.api.models.errors.removeModelFailed,
                    setActiveFailed: backendJa.modules.api.models.errors.setActiveModelFailed,
                },
            },
            promptSettings: {
                assemblyMode: {
                    description: backendJa.webview.promptSettings.assemblyMode.description,
                    entriesDescription: backendJa.webview.promptSettings.assemblyMode.entriesDescription,
                    entriesLabel: backendJa.webview.promptSettings.assemblyMode.entriesLabel,
                    legacyDescription: backendJa.webview.promptSettings.assemblyMode.legacyDescription,
                    legacyLabel: backendJa.webview.promptSettings.assemblyMode.legacyLabel,
                    title: backendJa.webview.promptSettings.assemblyMode.title,
                },
                dynamicSection: {
                    strategyDescription: backendJa.webview.promptSettings.dynamicSection.strategyDescription,
                    strategyPreserve: backendJa.webview.promptSettings.dynamicSection.strategyPreserve,
                    strategyPreserveWarning: backendJa.webview.promptSettings.dynamicSection.strategyPreserveWarning,
                    strategySingle: backendJa.webview.promptSettings.dynamicSection.strategySingle,
                    strategyTitle: backendJa.webview.promptSettings.dynamicSection.strategyTitle,
                    strategyVarsPrefix: backendJa.webview.promptSettings.dynamicSection.strategyVarsPrefix,
                    strategyVarsSeparator: backendJa.webview.promptSettings.dynamicSection.strategyVarsSeparator,
                    strategyVarsSuffix: backendJa.webview.promptSettings.dynamicSection.strategyVarsSuffix,
                    strategyVarsWarning: backendJa.webview.promptSettings.dynamicSection.strategyVarsWarning,
                },
            },
            subagents: {
                description: backendJa.tools.reviewDocument.finding.description,
            },
            toolSettings: {
                common: {
                    error: backendJa.modules.mcp.status.error,
                },
                files: {
                    applyDiff: {
                        diffGuardWarning: backendJa.tools.file.diffManager.diffGuardWarning,
                    },
                },
                terminal: {
                    executeCommand: {
                        execTimeout: backendJa.tools.errors.timeout,
                    },
                },
            },
            toolsSettings: {
                categories: {
                    other: backendJa.tools.reviewDocument.values.category.other,
                },
            },
        },
        subagents: {
            monitor: {
                resume: backendJa.notifications.windowsAgentStop.actionLabels.continue,
                status: {
                    completed: backendJa.tools.reviewDocument.values.milestoneStatus.completed,
                    failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
                },
            },
        },
        tools: {
            error: backendJa.modules.mcp.status.error,
            file: {
                createDirectoryPanel: {
                    failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
                },
                deleteFilePanel: {
                    failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
                },
            },
            media: {
                cropImagePanel: {
                    status: {
                        error: backendJa.modules.mcp.status.error,
                        failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
                generateImagePanel: {
                    status: {
                        error: backendJa.modules.mcp.status.error,
                        failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
                removeBackgroundPanel: {
                    status: {
                        error: backendJa.modules.mcp.status.error,
                        failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
                resizeImagePanel: {
                    status: {
                        error: backendJa.modules.mcp.status.error,
                        failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
                rotateImagePanel: {
                    status: {
                        error: backendJa.modules.mcp.status.error,
                        failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
            },
            reject: backendJa.tools.file.diffCodeLens.reject,
            subagents: {
                completed: backendJa.tools.reviewDocument.values.milestoneStatus.completed,
            },
            terminal: {
                executeCommandPanel: {
                    status: {
                        failed: backendJa.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
            },
        },
    },
    composables: {
        useAttachments: {
            errors: {
                readFileFailed: backendJa.webview.errors.readFileFailed,
            },
        },
    },
    errors: {
        cancelled: backendJa.errors.cancelled,
        unknown: backendJa.errors.unknown,
    },
    stores: {
        chatStore: {
            errors: {
                restoreCheckpointFailed: backendJa.modules.checkpoint.errors.restoreFailed,
                unknownError: backendJa.modules.api.chat.errors.unknownError,
            },
        },
        terminalStore: {
            errors: {
                killTerminalFailed: backendJa.webview.errors.killTerminalFailed,
            },
        },
    },
};

export default sharedJa;
