/**
 * AUTO-GENERATED by scripts/i18n-sync.mjs — 请勿手改！
 *
 * 共享词条生成物（单一来源：backend/i18n/langs/{zh-CN,en,ja}.ts + scripts/i18n-shared-manifest.json）。
 * 修改译文请改 backend 语言包；登记/调整共享映射请改 manifest，然后运行：
 *   node scripts/i18n-sync.mjs
 */

import backendZhCN from '../../../../../backend/i18n/langs/zh-CN';

const sharedZhCN = {
    app: {
        agentStopNotification: {
            actions: {
                continue: backendZhCN.notifications.windowsAgentStop.actionLabels.continue,
                executePlan: backendZhCN.notifications.windowsAgentStop.actionLabels.executePlan,
                generatePlan: backendZhCN.notifications.windowsAgentStop.actionLabels.generatePlan,
            },
        },
    },
    common: {
        completed: backendZhCN.tools.reviewDocument.values.milestoneStatus.completed,
        confirm: backendZhCN.notifications.windowsAgentStop.actionLabels.genericConfirmation,
        date: backendZhCN.tools.reviewDocument.header.date,
        description: backendZhCN.tools.reviewDocument.finding.description,
        error: backendZhCN.modules.mcp.status.error,
        failed: backendZhCN.notifications.windowsAgentStop.reasonLabels.error,
        hide: backendZhCN.tools.common.hide,
        resume: backendZhCN.notifications.windowsAgentStop.actionLabels.continue,
        show: backendZhCN.tools.common.show,
        status: backendZhCN.tools.reviewDocument.header.status,
        unknownError: backendZhCN.modules.api.chat.errors.unknownError,
    },
    components: {
        backgroundTasks: {
            completed: backendZhCN.tools.reviewDocument.values.milestoneStatus.completed,
            failed: backendZhCN.notifications.windowsAgentStop.reasonLabels.error,
        },
        channels: {
            anthropic: {
                thinking: {
                    displaySummarized: backendZhCN.tools.reviewDocument.milestone.summary,
                    effortLow: backendZhCN.tools.reviewDocument.values.severity.low,
                    effortMedium: backendZhCN.tools.reviewDocument.values.severity.medium,
                },
            },
            gemini: {
                thinking: {
                    levelHigh: backendZhCN.tools.reviewDocument.values.severity.high,
                    levelLow: backendZhCN.tools.reviewDocument.values.severity.low,
                    levelMedium: backendZhCN.tools.reviewDocument.values.severity.medium,
                },
            },
            openai: {
                thinking: {
                    effortHigh: backendZhCN.tools.reviewDocument.values.severity.high,
                    effortLow: backendZhCN.tools.reviewDocument.values.severity.low,
                    effortMedium: backendZhCN.tools.reviewDocument.values.severity.medium,
                },
            },
        },
        common: {
            confirmDialog: {
                confirm: backendZhCN.notifications.windowsAgentStop.actionLabels.genericConfirmation,
                title: backendZhCN.notifications.windowsAgentStop.actionLabels.genericConfirmation,
            },
        },
        input: {
            fileNotExists: backendZhCN.webview.errors.fileNotExists,
            notifications: {
                fileInOtherWorkspace: backendZhCN.webview.errors.fileInOtherWorkspace,
                fileNotInAnyWorkspace: backendZhCN.webview.errors.fileNotInAnyWorkspace,
            },
            promptContext: {
                readFailed: backendZhCN.webview.errors.readFileFailed,
            },
        },
        message: {
            checkpoint: {
                restoreResultFailed: backendZhCN.modules.checkpoint.errors.restoreFailed,
            },
            continue: {
                button: backendZhCN.notifications.windowsAgentStop.actionLabels.continue,
            },
            responseViewer: {
                status: backendZhCN.tools.reviewDocument.header.status,
                toolStatuses: {
                    error: backendZhCN.notifications.windowsAgentStop.reasonLabels.error,
                },
            },
            tool: {
                designCard: {
                    generatePlan: backendZhCN.notifications.windowsAgentStop.actionLabels.generatePlan,
                    openFileFailed: backendZhCN.webview.errors.openFileFailed,
                },
                error: backendZhCN.modules.mcp.status.error,
                openDiffFailed: backendZhCN.webview.errors.openDiffPreviewFailed,
                planCard: {
                    executePlan: backendZhCN.notifications.windowsAgentStop.actionLabels.executePlan,
                    openFileFailed: backendZhCN.webview.errors.openFileFailed,
                },
                progressCard: {
                    currentProgress: backendZhCN.tools.reviewDocument.summary.currentProgress,
                    issueError: backendZhCN.modules.mcp.status.error,
                    latestConclusion: backendZhCN.tools.reviewDocument.summary.latestConclusion,
                    milestoneStatusCompleted: backendZhCN.tools.reviewDocument.values.milestoneStatus.completed,
                    milestoneStatusInProgress: backendZhCN.tools.reviewDocument.values.milestoneStatus.inProgress,
                    status: backendZhCN.tools.reviewDocument.milestone.status,
                    statusActive: backendZhCN.tools.reviewDocument.values.milestoneStatus.inProgress,
                    statusCompleted: backendZhCN.tools.reviewDocument.values.milestoneStatus.completed,
                },
                reject: backendZhCN.tools.file.diffCodeLens.reject,
                rejectAll: backendZhCN.tools.file.diffCodeLens.rejectAll,
                reviewCard: {
                    categoryAccessibility: backendZhCN.tools.reviewDocument.values.category.accessibility,
                    categoryCss: backendZhCN.tools.reviewDocument.values.category.css,
                    categoryDocs: backendZhCN.tools.reviewDocument.values.category.docs,
                    categoryHtml: backendZhCN.tools.reviewDocument.values.category.html,
                    categoryJavascript: backendZhCN.tools.reviewDocument.values.category.javascript,
                    categoryMaintainability: backendZhCN.tools.reviewDocument.values.category.maintainability,
                    categoryOther: backendZhCN.tools.reviewDocument.values.category.other,
                    categoryPerformance: backendZhCN.tools.reviewDocument.values.category.performance,
                    categoryTest: backendZhCN.tools.reviewDocument.values.category.test,
                    changeDescription: backendZhCN.tools.reviewDocument.finding.description,
                    changeEvidence: backendZhCN.tools.reviewDocument.finding.evidenceFiles,
                    changeRecommendation: backendZhCN.tools.reviewDocument.finding.recommendation,
                    changeRelatedMilestoneIds: backendZhCN.tools.reviewDocument.finding.relatedMilestones,
                    changeSeverity: backendZhCN.tools.reviewDocument.finding.severity,
                    changeTrackingStatus: backendZhCN.tools.reviewDocument.finding.trackingStatus,
                    decision: backendZhCN.tools.reviewDocument.milestone.conclusion,
                    decisionAccepted: backendZhCN.tools.reviewDocument.values.overallDecision.accepted,
                    decisionConditionallyAccepted: backendZhCN.tools.reviewDocument.values.overallDecision.conditionallyAccepted,
                    decisionRejected: backendZhCN.tools.reviewDocument.values.overallDecision.rejected,
                    evidence: backendZhCN.tools.reviewDocument.milestone.evidenceFiles,
                    findings: backendZhCN.tools.reviewDocument.milestone.findings,
                    generatePlan: backendZhCN.notifications.windowsAgentStop.actionLabels.generatePlan,
                    issueError: backendZhCN.modules.mcp.status.error,
                    latestConclusion: backendZhCN.tools.reviewDocument.summary.latestConclusion,
                    modules: backendZhCN.tools.reviewDocument.summary.reviewedModules,
                    recommendedNextAction: backendZhCN.tools.reviewDocument.summary.recommendedNextAction,
                    severityHigh: backendZhCN.tools.reviewDocument.values.severity.high,
                    severityLow: backendZhCN.tools.reviewDocument.values.severity.low,
                    severityMedium: backendZhCN.tools.reviewDocument.values.severity.medium,
                    status: backendZhCN.tools.reviewDocument.header.status,
                    statusCompleted: backendZhCN.tools.reviewDocument.values.milestoneStatus.completed,
                    statusInProgress: backendZhCN.tools.reviewDocument.values.milestoneStatus.inProgress,
                    tracking: backendZhCN.tools.reviewDocument.finding.trackingStatus,
                    trackingAcceptedRisk: backendZhCN.tools.reviewDocument.values.trackingStatus.acceptedRisk,
                    trackingDuplicate: backendZhCN.tools.reviewDocument.values.trackingStatus.duplicate,
                    trackingFixed: backendZhCN.tools.reviewDocument.values.trackingStatus.fixed,
                    trackingOpen: backendZhCN.tools.reviewDocument.values.trackingStatus.open,
                    trackingWontFix: backendZhCN.tools.reviewDocument.values.trackingStatus.wontFix,
                },
                todoPanel: {
                    statusCompleted: backendZhCN.tools.reviewDocument.values.milestoneStatus.completed,
                    statusInProgress: backendZhCN.tools.reviewDocument.values.milestoneStatus.inProgress,
                },
            },
        },
        settings: {
            autoExec: {
                categories: {
                    other: backendZhCN.tools.reviewDocument.values.category.other,
                },
            },
            channelSettings: {
                dialog: {
                    delete: {
                        confirm: backendZhCN.notifications.windowsAgentStop.actionLabels.genericConfirmation,
                    },
                },
                form: {
                    multimodal: {
                        document: backendZhCN.tools.reviewDocument.values.category.docs,
                    },
                },
                selector: {
                    confirm: backendZhCN.notifications.windowsAgentStop.actionLabels.genericConfirmation,
                },
            },
            checkpoint: {
                sections: {
                    cleanup: {
                        manifestNote: backendZhCN.modules.checkpoint.restore.excludedNote,
                        phaseAfter: backendZhCN.modules.checkpoint.description.after,
                        phaseBefore: backendZhCN.modules.checkpoint.description.before,
                        progress: {
                            failed: backendZhCN.notifications.windowsAgentStop.reasonLabels.error,
                        },
                    },
                    tools: {
                        afterLabel: backendZhCN.modules.checkpoint.description.after,
                        beforeLabel: backendZhCN.modules.checkpoint.description.before,
                    },
                },
            },
            contextSettings: {
                diagnostics: {
                    severity: {
                        error: backendZhCN.modules.mcp.status.error,
                    },
                },
            },
            dependencySettings: {
                progress: {
                    installSuccess: backendZhCN.modules.dependencies.progress.installSuccess,
                    unknownError: backendZhCN.modules.api.chat.errors.unknownError,
                },
            },
            mcp: {
                connected: backendZhCN.modules.mcp.status.connected,
                disconnected: backendZhCN.modules.mcp.status.disconnected,
                error: backendZhCN.modules.mcp.status.error,
            },
            mcpSettings: {
                form: {
                    description: backendZhCN.tools.reviewDocument.finding.description,
                    serverIdError: backendZhCN.modules.mcp.errors.invalidServerId,
                },
                serverCard: {
                    connecting: backendZhCN.modules.mcp.status.connecting,
                },
                status: {
                    connected: backendZhCN.modules.mcp.status.connected,
                    connecting: backendZhCN.modules.mcp.status.connecting,
                },
            },
            modelManager: {
                errors: {
                    addFailed: backendZhCN.modules.api.models.errors.addModelsFailed,
                    removeFailed: backendZhCN.modules.api.models.errors.removeModelFailed,
                    setActiveFailed: backendZhCN.modules.api.models.errors.setActiveModelFailed,
                },
            },
            promptSettings: {
                assemblyMode: {
                    description: backendZhCN.webview.promptSettings.assemblyMode.description,
                    entriesDescription: backendZhCN.webview.promptSettings.assemblyMode.entriesDescription,
                    entriesLabel: backendZhCN.webview.promptSettings.assemblyMode.entriesLabel,
                    legacyDescription: backendZhCN.webview.promptSettings.assemblyMode.legacyDescription,
                    legacyLabel: backendZhCN.webview.promptSettings.assemblyMode.legacyLabel,
                    title: backendZhCN.webview.promptSettings.assemblyMode.title,
                },
                dynamicSection: {
                    strategyDescription: backendZhCN.webview.promptSettings.dynamicSection.strategyDescription,
                    strategyPreserve: backendZhCN.webview.promptSettings.dynamicSection.strategyPreserve,
                    strategyPreserveWarning: backendZhCN.webview.promptSettings.dynamicSection.strategyPreserveWarning,
                    strategySingle: backendZhCN.webview.promptSettings.dynamicSection.strategySingle,
                    strategyTitle: backendZhCN.webview.promptSettings.dynamicSection.strategyTitle,
                    strategyVarsPrefix: backendZhCN.webview.promptSettings.dynamicSection.strategyVarsPrefix,
                    strategyVarsSeparator: backendZhCN.webview.promptSettings.dynamicSection.strategyVarsSeparator,
                    strategyVarsSuffix: backendZhCN.webview.promptSettings.dynamicSection.strategyVarsSuffix,
                    strategyVarsWarning: backendZhCN.webview.promptSettings.dynamicSection.strategyVarsWarning,
                },
            },
            subagents: {
                description: backendZhCN.tools.reviewDocument.finding.description,
            },
            toolSettings: {
                common: {
                    error: backendZhCN.modules.mcp.status.error,
                },
                files: {
                    applyDiff: {
                        diffGuardWarning: backendZhCN.tools.file.diffManager.diffGuardWarning,
                    },
                },
                terminal: {
                    executeCommand: {
                        execTimeout: backendZhCN.tools.errors.timeout,
                    },
                },
            },
            toolsSettings: {
                categories: {
                    other: backendZhCN.tools.reviewDocument.values.category.other,
                },
            },
        },
        subagents: {
            monitor: {
                resume: backendZhCN.notifications.windowsAgentStop.actionLabels.continue,
                status: {
                    completed: backendZhCN.tools.reviewDocument.values.milestoneStatus.completed,
                    failed: backendZhCN.notifications.windowsAgentStop.reasonLabels.error,
                },
            },
        },
        tools: {
            error: backendZhCN.modules.mcp.status.error,
            file: {
                createDirectoryPanel: {
                    failed: backendZhCN.notifications.windowsAgentStop.reasonLabels.error,
                },
                deleteFilePanel: {
                    failed: backendZhCN.notifications.windowsAgentStop.reasonLabels.error,
                },
            },
            media: {
                cropImagePanel: {
                    status: {
                        error: backendZhCN.modules.mcp.status.error,
                        failed: backendZhCN.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
                generateImagePanel: {
                    status: {
                        error: backendZhCN.modules.mcp.status.error,
                        failed: backendZhCN.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
                removeBackgroundPanel: {
                    status: {
                        error: backendZhCN.modules.mcp.status.error,
                        failed: backendZhCN.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
                resizeImagePanel: {
                    status: {
                        error: backendZhCN.modules.mcp.status.error,
                        failed: backendZhCN.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
                rotateImagePanel: {
                    status: {
                        error: backendZhCN.modules.mcp.status.error,
                        failed: backendZhCN.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
            },
            reject: backendZhCN.tools.file.diffCodeLens.reject,
            subagents: {
                completed: backendZhCN.tools.reviewDocument.values.milestoneStatus.completed,
            },
            terminal: {
                executeCommandPanel: {
                    status: {
                        failed: backendZhCN.notifications.windowsAgentStop.reasonLabels.error,
                    },
                },
            },
        },
    },
    composables: {
        useAttachments: {
            errors: {
                readFileFailed: backendZhCN.webview.errors.readFileFailed,
            },
        },
    },
    errors: {
        cancelled: backendZhCN.errors.cancelled,
        unknown: backendZhCN.errors.unknown,
    },
    stores: {
        chatStore: {
            errors: {
                restoreCheckpointFailed: backendZhCN.modules.checkpoint.errors.restoreFailed,
                unknownError: backendZhCN.modules.api.chat.errors.unknownError,
            },
        },
        terminalStore: {
            errors: {
                killTerminalFailed: backendZhCN.webview.errors.killTerminalFailed,
            },
        },
    },
};

export default sharedZhCN;
