/**
 * AUTO-GENERATED by scripts/generate-tool-meta.mjs — 请勿手改！
 *
 * 单一来源：backend/tools 下各工具文件的 ToolDeclaration（工具名 / description / 参数 schema）。
 * 只包含「可静态求值」的确定性字段；运行时动态构造的 description/参数被省略并置
 * descriptionDynamic / parametersDynamic 标记（前端据此回退手写文案）。
 * 重新生成：node scripts/generate-tool-meta.mjs
 */
export interface ToolMetaParameterItem {
  type: string
  description?: string
  enum?: string[]
}

export interface ToolMetaParameter {
  type: string
  description?: string
  enum?: string[]
  default?: string | number | boolean
  required?: boolean
  items?: ToolMetaParameterItem
}

export interface ToolMeta {
  /** 工具声明描述（仅静态可提取；运行时动态构造时省略并置 descriptionDynamic） */
  description?: string
  descriptionDynamic?: boolean
  /** 顶层参数摘要：参数名 → { type, description?, enum?, default?, required?, items? } */
  parameters: Record<string, ToolMetaParameter>
  /** parameters 存在无法静态提取的部分时为 true */
  parametersDynamic?: boolean
  /** 声明来源（backend/tools 相对路径），便于核对 */
  source: string
}

export const toolMeta: Record<string, ToolMeta> = {
  'agent_send_message': {
    descriptionDynamic: true,
    parameters: {
      "targetRunId": {"type":"string"},
      "targetAgentName": {"type":"string"},
      "message": {"type":"string","required":true},
      "threadId": {"type":"string"},
    },
    parametersDynamic: true,
    source: "backend/tools/subagents/agentSendMessage.ts",
  },
  'apply_diff': {
    descriptionDynamic: true,
    parameters: {
      "path": {"type":"string","required":true},
      "hunks": {"type":"array","items":{"type":"object"}},
      "patch": {"type":"string"},
    },
    parametersDynamic: true,
    source: "backend/tools/file/diff/declaration.ts",
  },
  'compare_review_documents': {
    description: "Compare two review documents under .graycode/review/**.md without modifying them. Returns finding deltas, tracking changes, and snapshot statistics differences.",
    parameters: {
      "basePath": {"type":"string","description":"Base review document path under .graycode/review/**.md","required":true},
      "targetPath": {"type":"string","description":"Target review document path under .graycode/review/**.md","required":true},
      "includeUnchanged": {"type":"boolean","description":"Whether to include unchanged persisted findings in the result"},
    },
    source: "backend/tools/review/compare_review_documents.ts",
  },
  'create_design': {
    description: "Create a design document (markdown) and write it under .graycode/design/**.md. This tool only creates the design; it does NOT create a plan or implement code.",
    parameters: {
      "title": {"type":"string","description":"Optional design title (used for default filename)"},
      "overview": {"type":"string","description":"Optional one-line overview"},
      "design": {"type":"string","description":"Design content in markdown","required":true},
      "path": {"type":"string","description":"Optional output path. Must be under .graycode/design/**.md (or multi-root: workspace/.graycode/design/**.md)."},
    },
    source: "backend/tools/design/create_design.ts",
  },
  'create_directory': {
    descriptionDynamic: true,
    parameters: {
      "paths": {"type":"array","items":{"type":"string"},"required":true},
    },
    parametersDynamic: true,
    source: "backend/tools/file/create_directory.ts",
  },
  'create_plan': {
    description: "Create a plan document (markdown) and write it under .graycode/plans/**.md. This tool only creates the plan; it does NOT execute it.",
    parameters: {
      "title": {"type":"string","description":"Optional plan title (used for default filename)"},
      "overview": {"type":"string","description":"Optional one-line overview"},
      "plan": {"type":"string","description":"Plan content in markdown","required":true},
      "todos": {"type":"array","description":"Optional TODO checklist (Cursor-style)","items":{"type":"object"},"required":true},
      "sourceArtifact": {"type":"object","description":"Optional source artifact to track plan freshness against a confirmed design or review."},
      "path": {"type":"string","description":"Optional output path. Must be under .graycode/plans/**.md (or multi-root: workspace/.graycode/plans/**.md)."},
    },
    source: "backend/tools/plan/create_plan.ts",
  },
  'create_progress': {
    description: "Create the project progress document at .graycode/progress.md. This initializes the project-level status ledger and returns a lightweight progress snapshot instead of the full markdown body.",
    parameters: {
      "path": {"type":"string","description":"Optional output path. Must be .graycode/progress.md (or multi-root: workspace/.graycode/progress.md)."},
      "projectName": {"type":"string","description":"Optional human-readable project name."},
      "projectId": {"type":"string","description":"Optional stable project id. Defaults to a slug from the project name."},
      "status": {"type":"string","enum":["active","blocked","completed","archived"]},
      "phase": {"type":"string","enum":["design","plan","implementation","review","maintenance"]},
      "currentFocus": {"type":"string"},
      "latestConclusion": {"type":"string"},
      "currentBlocker": {"type":"string"},
      "nextAction": {"type":"string"},
      "activeArtifacts": {"type":"object"},
      "todos": {"type":"array","items":{"type":"object"}},
      "risks": {"type":"array","items":{"type":"object"}},
    },
    source: "backend/tools/progress/create_progress.ts",
  },
  'create_review': {
    description: "Create a review document (markdown) and write it under .graycode/review/**.md. This tool is for Review mode and must not modify business code.",
    parameters: {
      "title": {"type":"string","description":"Optional review title (used for default filename)"},
      "overview": {"type":"string","description":"Optional one-line review overview"},
      "review": {"type":"string","description":"Initial review content in markdown","required":true},
      "path": {"type":"string","description":"Optional output path. Must be under .graycode/review/**.md (or multi-root: workspace/.graycode/review/**.md)."},
    },
    source: "backend/tools/review/create_review.ts",
  },
  'crop_image': {
    descriptionDynamic: true,
    parameters: {
      "images": {"type":"array","items":{"type":"object"}},
      "image_path": {"type":"string"},
      "output_path": {"type":"string"},
      "x1": {"type":"integer"},
      "y1": {"type":"integer"},
      "x2": {"type":"integer"},
      "y2": {"type":"integer"},
    },
    parametersDynamic: true,
    source: "backend/tools/media/crop_image.ts",
  },
  'delete_code': {
    descriptionDynamic: true,
    parameters: {
      "files": {"type":"array","items":{"type":"object"},"required":true},
    },
    parametersDynamic: true,
    source: "backend/tools/file/delete_code.ts",
  },
  'delete_file': {
    descriptionDynamic: true,
    parameters: {
      "paths": {"type":"array","items":{"type":"string"},"required":true},
    },
    parametersDynamic: true,
    source: "backend/tools/file/delete_file.ts",
  },
  'execute_command': {
    descriptionDynamic: true,
    parameters: {
      "command": {"type":"string","required":true},
      "cwd": {"type":"string"},
      "shell": {"type":"string","default":"default"},
      "timeout": {"type":"number","default":60000},
      "background": {"type":"boolean"},
    },
    parametersDynamic: true,
    source: "backend/tools/terminal/processRunner.ts",
  },
  'finalize_review': {
    description: "Finalize an existing review document under .graycode/review/**.md, normalize its structure, and update the final review summary.",
    parameters: {
      "path": {"type":"string","description":"Target review document path under .graycode/review/**.md","required":true},
      "conclusion": {"type":"string","description":"Final review conclusion","required":true},
      "overallDecision": {"type":"string","description":"Optional overall review decision","enum":["accepted","conditionally_accepted","rejected","needs_follow_up"]},
      "recommendedNextAction": {"type":"string","description":"Optional recommended next action for the summary section"},
      "reviewedModules": {"type":"array","description":"Optional reviewed modules to merge into the summary section","items":{"type":"string"}},
    },
    source: "backend/tools/review/finalize_review.ts",
  },
  'find_files': {
    descriptionDynamic: true,
    parameters: {
      "patterns": {"type":"array","items":{"type":"string"},"required":true},
      "exclude": {"type":"string","default":"**/node_modules/**"},
      "maxResults": {"type":"number","default":500},
    },
    parametersDynamic: true,
    source: "backend/tools/search/find_files.ts",
  },
  'find_references': {
    descriptionDynamic: true,
    parameters: {
      "path": {"type":"string","required":true},
      "line": {"type":"integer","required":true},
      "column": {"type":"integer"},
      "symbol": {"type":"string"},
      "context": {"type":"number"},
    },
    parametersDynamic: true,
    source: "backend/tools/lsp/find_references.ts",
  },
  'generate_image': {
    descriptionDynamic: true,
    parameters: {
      "images": {"type":"array","items":{"type":"object"}},
    },
    parametersDynamic: true,
    source: "backend/tools/media/generate_image.ts",
  },
  'get_activity_stats': {
    description: "Get the user's IDE usage time statistics: daily usage minutes, recent schedule (hourly heatmap of when the user is active), and how long the user has been continuously working. Use this to understand the user's work-rest rhythm, detect long continuous working sessions, or check whether the user is currently active. Data contains timestamps only, no user content. Returned times are in local time (HH:mm, YYYY-MM-DD).",
    parameters: {
      "range": {"type":"string","description":"Statistics range: today / 7d (last 7 days) / 30d / 90d / 365d / all (entire history). Default: 7d.","enum":["today","7d","30d","90d","365d","all"]},
      "includeHourly": {"type":"boolean","description":"Whether to include the hourly heatmap (24 slots per day, active minutes per hour, local time). Useful for analyzing the user's sleep/work schedule. Default: false."},
      "includeMonthly": {"type":"boolean","description":"Whether to include monthly aggregates (total minutes, active days, session count per month). Useful for long-term usage overview. Default: false."},
    },
    source: "backend/tools/activity/activity_stats.ts",
  },
  'get_symbols': {
    descriptionDynamic: true,
    parameters: {
      "paths": {"type":"array","items":{"type":"string"},"required":true},
    },
    parametersDynamic: true,
    source: "backend/tools/lsp/get_symbols.ts",
  },
  'goto_definition': {
    descriptionDynamic: true,
    parameters: {
      "path": {"type":"string","required":true},
      "line": {"type":"integer","required":true},
      "column": {"type":"integer"},
      "symbol": {"type":"string"},
    },
    parametersDynamic: true,
    source: "backend/tools/lsp/goto_definition.ts",
  },
  'history_search': {
    descriptionDynamic: true,
    parameters: {
      "mode": {"type":"string","enum":["search","read"],"required":true},
      "query": {"type":"string"},
      "is_regex": {"type":"boolean"},
      "start_line": {"type":"integer"},
      "end_line": {"type":"integer"},
    },
    parametersDynamic: true,
    source: "backend/tools/history/history_search.ts",
  },
  'insert_code': {
    descriptionDynamic: true,
    parameters: {
      "files": {"type":"array","items":{"type":"object"},"required":true},
    },
    parametersDynamic: true,
    source: "backend/tools/file/insert_code.ts",
  },
  'list_files': {
    descriptionDynamic: true,
    parameters: {
      "paths": {"type":"array","items":{"type":"string"},"required":true},
      "recursive": {"type":"boolean","default":false},
    },
    parametersDynamic: true,
    source: "backend/tools/file/list_files.ts",
  },
  'memory_compress': {
    description: "执行待处理的记忆压缩合并。\n记忆系统使用二叉树结构：相邻记忆两两合并为一行摘要，摘要再合并。\nmemory_note 可能会返回压缩提示——按顺序执行它们。\n参数：blockId（块 ID，如 \"0-1\"）；summary（压缩后的摘要文本，一行，长度受 entryChars 上限约束，默认 ≤280 字节）。\n不传参数时，返回下一个待压缩的提示。\n作用域：有工作区时默认作用于当前工作区记忆；如需操作全局记忆请传 scope=\"global\"。",
    parameters: {
      "blockId": {"type":"string","description":"要压缩的块 ID（如 \"0-1\"）。从压缩提示中复制。"},
      "summary": {"type":"string","description":"压缩后的摘要文本。一行，长度受 entryChars 上限约束（默认最多 280 字节）。保留有持久影响的内容，丢弃不再重要的。不要编造。"},
      "scope": {"type":"string","description":"记忆作用域。有工作区时默认作用于当前工作区记忆；如需操作全局记忆请传 \"global\"，如需显式操作工作区记忆请传 \"workspace\"。","enum":["global","workspace"]},
    },
    source: "backend/tools/memory/memory_compress.ts",
  },
  'memory_config': {
    description: "查看或修改永久记忆系统的配置参数。\n可配置项：\n- wakeLines: wake 输出的行数预算（默认 96，≈8k tokens）\n- entryChars: 单条记忆最大字节数（默认 280，上限 1000）\n不传参数时显示当前配置。传参数时修改对应项。\n修改只影响输出格式，不需要重新计算任何东西。",
    parameters: {
      "wakeLines": {"type":"number","description":"wake 输出的行数预算。更大的值 = 更多细节。"},
      "entryChars": {"type":"number","description":"单条记忆最大字节数。默认 280，上限 1000（固定宽度记录约束，含记录头部开销）。"},
    },
    source: "backend/tools/memory/memory_config.ts",
  },
  'memory_forget': {
    description: "丢弃错误的树摘要，或删除原始记忆。\n当 blockId 是范围（如 \"16-31\"，破折号）：仅丢弃树摘要及其上层摘要，原始记忆（LOG）不会被触碰。\n当 blockId 是单个数字（如 \"5\"）：删除这一条原始记忆（其后的记录 id 前移重编号）。\n当 blockId 是闭区间（如 \"1,3\"，逗号分隔）：删除 ID 1 到 3 的所有原始记忆（含端点）。\n参数：blockId（块 ID 如 \"16-31\"、单个 ID 如 \"5\"、或闭区间如 \"1,3\"）。\n作用域：有工作区时默认作用于当前工作区记忆；如需操作全局记忆请传 scope=\"global\"。",
    parameters: {
      "blockId": {"type":"string","description":"块 ID（如 \"16-31\"）丢弃树摘要；单个 ID（如 \"5\"）删除这一条记忆；闭区间（如 \"1,3\"）删除 1 到 3 的所有记忆。","required":true},
      "scope": {"type":"string","description":"记忆作用域。有工作区时默认作用于当前工作区记忆；如需操作全局记忆请传 \"global\"，如需显式操作工作区记忆请传 \"workspace\"。","enum":["global","workspace"]},
    },
    source: "backend/tools/memory/memory_forget.ts",
  },
  'memory_note': {
    description: "记录一条永久记忆。当你学到新东西、发生值得记住的事情时调用。\n记忆保存到当前工作区的记忆存储（与全局记忆分开，memory_wake 会同时读取两者）。\n一行文本，长度受 memory_config 的 entryChars 上限控制（默认最多 280 字符，按字节计，重音字符占 2 字节；可经 memory_config 调高至 1000）。\n不要记录冗余的、已经知道的或刚才已经记录过的内容。\n如果返回了压缩提示（pendingCompression），请在下一次操作前执行 memory_compress。",
    parameters: {
      "text": {"type":"string","description":"要记录的记忆文本。一行，长度受 memory_config 的 entryChars 上限控制（默认最多 280 字符）。","required":true},
    },
    source: "backend/tools/memory/memory_note.ts",
  },
  'memory_recall': {
    description: "搜索全部永久记忆（逐字匹配）。支持正则表达式。\n搜索范围包括全局记忆与当前工作区记忆（按工作区隔离），命中结果以 --- Global memory --- / --- Workspace memory --- 标注来源。\n搜索范围包括已被压缩摘要的原始记忆——压缩不会丢失信息。\n结果限制在单次输出容量内，如果被截断会提示缩小正则范围。",
    parameters: {
      "regex": {"type":"string","description":"搜索正则表达式（大小写不敏感）。搜索范围包括 ID 和日期。","required":true},
    },
    source: "backend/tools/memory/memory_recall.ts",
  },
  'memory_wake': {
    description: "唤醒永久记忆。在每次会话开始时、做任何其他事情之前必须先调用此工具。\n输出包含两部分：全局记忆与当前工作区记忆（按工作区隔离），以 --- Global memory --- / --- Workspace memory --- 标注。\n它会一次输出你的全部可用记忆：近期的记忆保持原文，远期的记忆被压缩为摘要。\n不需要任何参数。",
    parameters: {
    },
    parametersDynamic: true,
    source: "backend/tools/memory/memory_wake.ts",
  },
  'memory_zoom': {
    description: "展开一个记忆树节点，查看它的两个半部分。\n记忆形成一棵二叉树：memory_wake 输出的每一行 #a-b 都是一个节点。\n用 memory_zoom 可以展开它，看到下一层的两个半部分，直到原始记忆本身。\n参数：blockId（块 ID，如 \"16-31\"）。\n作用域：有工作区时默认读取当前工作区记忆；如需读取全局记忆请传 scope=\"global\"。",
    parameters: {
      "blockId": {"type":"string","description":"要展开的块 ID（如 \"16-31\"）。从 wake 输出或上一次 zoom 的结果中复制。","required":true},
      "scope": {"type":"string","description":"记忆作用域。有工作区时默认读取当前工作区记忆；如需读取全局记忆请传 \"global\"，如需显式读取工作区记忆请传 \"workspace\"。","enum":["global","workspace"]},
    },
    source: "backend/tools/memory/memory_zoom.ts",
  },
  'read_file': {
    descriptionDynamic: true,
    parameters: {
      "path": {"type":"string"},
      "files": {"type":"array","items":{"type":"object"}},
      "startLine": {"type":"integer"},
      "endLine": {"type":"integer"},
    },
    parametersDynamic: true,
    source: "backend/tools/file/read_file.ts",
  },
  'read_skill': {
    descriptionDynamic: true,
    parameters: {
      "name": {"type":"string","required":true},
    },
    parametersDynamic: true,
    source: "backend/tools/skills/readSkill.ts",
  },
  'record_progress_milestone': {
    description: "Record a project milestone into .graycode/progress.md and refresh the latest progress snapshot. This is for project-level progress nodes, not for full review findings or plan documents.",
    parameters: {
      "path": {"type":"string","description":"Optional target path. Must be .graycode/progress.md (or multi-root: workspace/.graycode/progress.md)."},
      "milestoneId": {"type":"string"},
      "title": {"type":"string","required":true},
      "status": {"type":"string","enum":["in_progress","completed"]},
      "summary": {"type":"string","required":true},
      "relatedTodoIds": {"type":"array","items":{"type":"string"}},
      "relatedReviewMilestoneIds": {"type":"array","items":{"type":"string"}},
      "relatedArtifacts": {"type":"object"},
      "startedAt": {"type":"string"},
      "completedAt": {"type":"string"},
      "nextAction": {"type":"string"},
      "latestConclusion": {"type":"string"},
      "currentBlocker": {"type":"string"},
    },
    source: "backend/tools/progress/record_progress_milestone.ts",
  },
  'record_review_milestone': {
    description: "Append a milestone to an existing review document under .graycode/review/**.md and update the structured summary sections.",
    parameters: {
      "path": {"type":"string","description":"Target review document path under .graycode/review/**.md","required":true},
      "milestoneId": {"type":"string","description":"Optional milestone identifier. If omitted, it is generated automatically."},
      "milestoneTitle": {"type":"string","description":"Milestone title","required":true},
      "summary": {"type":"string","description":"Milestone summary in markdown","required":true},
      "status": {"type":"string","description":"Milestone status","enum":["in_progress","completed"]},
      "conclusion": {"type":"string","description":"Optional latest conclusion for the summary section"},
      "evidenceFiles": {"type":"array","description":"Optional related evidence file paths. Use this for simple file-level evidence when line-level references are not available.","items":{"type":"string"}},
      "evidence": {"type":"array","description":"Optional structured evidence references with file path and optional line or symbol details.","items":{"type":"object"}},
      "findings": {"type":"array","description":"Optional legacy finding strings to merge into the review findings section","items":{"type":"string"}},
      "structuredFindings": {"type":"array","description":"Optional structured findings to merge into the review findings section. Keep title concise, and put detailed explanation into description.","items":{"type":"object"}},
      "reviewedModules": {"type":"array","description":"Optional reviewed modules to merge into the review summary section","items":{"type":"string"}},
      "recommendedNextAction": {"type":"string","description":"Optional recommended next action for the review summary section"},
    },
    source: "backend/tools/review/record_review_milestone.ts",
  },
  'remove_background': {
    descriptionDynamic: true,
    parameters: {
      "images": {"type":"array","items":{"type":"object"}},
      "image_path": {"type":"string"},
      "output_path": {"type":"string"},
      "subject_description": {"type":"string"},
      "mask_path": {"type":"string"},
    },
    parametersDynamic: true,
    source: "backend/tools/media/remove_background.ts",
  },
  'reopen_review': {
    description: "Reopen a finalized review document under .graycode/review/**.md so the same review run can continue recording milestones.",
    parameters: {
      "path": {"type":"string","description":"Target finalized review document path under .graycode/review/**.md","required":true},
    },
    source: "backend/tools/review/reopen_review.ts",
  },
  'resize_image': {
    descriptionDynamic: true,
    parameters: {
      "images": {"type":"array","items":{"type":"object"}},
      "image_path": {"type":"string"},
      "output_path": {"type":"string"},
      "width": {"type":"integer"},
      "height": {"type":"integer"},
    },
    parametersDynamic: true,
    source: "backend/tools/media/resize_image.ts",
  },
  'rotate_image': {
    descriptionDynamic: true,
    parameters: {
      "images": {"type":"array","items":{"type":"object"}},
      "image_path": {"type":"string"},
      "output_path": {"type":"string"},
      "angle": {"type":"number"},
      "format": {"type":"string"},
    },
    parametersDynamic: true,
    source: "backend/tools/media/rotate_image.ts",
  },
  'sandbox': {
    parameters: {
      "language": {"type":"string","description":"Programming language of the code to run.","required":true},
      "code": {"type":"string","description":"The source code to execute.","required":true},
      "stdin": {"type":"string","description":"Optional input to pass to the program via standard input."},
      "timeout": {"type":"number","description":"Optional timeout in milliseconds. Capped by the configured default timeout."},
    },
    parametersDynamic: true,
    source: "backend/tools/sandbox/sandbox.ts",
  },
  'search_in_files': {
    descriptionDynamic: true,
    parameters: {
      "mode": {"type":"string","enum":["search","replace"],"default":"search"},
      "query": {"type":"string","required":true},
      "path": {"type":"string","default":"."},
      "pattern": {"type":"string","default":"**/*"},
      "isRegex": {"type":"boolean","default":false},
      "caseSensitive": {"type":"boolean"},
      "maxResults": {"type":"number","default":100},
      "replace": {"type":"string"},
      "maxFiles": {"type":"number","default":50},
    },
    parametersDynamic: true,
    source: "backend/tools/search/declaration.ts",
  },
  'show_windows_notification': {
    description: "Show a Windows system notification with a custom title and message. Use this when you need to notify the user outside the chat UI, for example when a long task finishes, user action is needed, or an important status changes. On non-Windows platforms the tool reports that notification is unsupported.",
    parameters: {
      "title": {"type":"string","description":"Notification title. Keep it short and clear.","required":true},
      "message": {"type":"string","description":"Notification body text. Summarize the important information for the user.","required":true},
      "silent": {"type":"boolean","description":"Whether to suppress notification sound. Default: true."},
      "openChatOnClick": {"type":"boolean","description":"Whether clicking the notification should open the GrayCode chat view. Default: true."},
    },
    source: "backend/tools/notification/show_windows_notification.ts",
  },
  'subagents': {
    descriptionDynamic: true,
    parameters: {
      "agentName": {"type":"string","required":true},
      "prompt": {"type":"string","required":true},
      "context": {"type":"string"},
      "continueFromRunId": {"type":"string"},
      "background": {"type":"boolean"},
    },
    parametersDynamic: true,
    source: "backend/tools/subagents/subagents.ts",
  },
  'todo_update': {
    description: "Incrementally update the per-conversation TODO list stored in ConversationMetadata.custom[\"todoList\"]. Use this to update status/content without rewriting the entire list.",
    parameters: {
      "ops": {"type":"array","description":"Operations to apply to the current TODO list","items":{"type":"object"},"required":true},
    },
    source: "backend/tools/todo/todo_update.ts",
  },
  'todo_write': {
    description: "Create/replace the per-conversation TODO list (ConversationMetadata.custom[\"todoList\"]). IMPORTANT: Use this tool to initialize the list. For incremental updates (status/content), use todo_update.",
    parameters: {
      "todos": {"type":"array","description":"Array of todo items","items":{"type":"object"},"required":true},
    },
    source: "backend/tools/todo/todo_write.ts",
  },
  'toggle_skills': {
    description: "Enable or disable skills for subsequent requests. Skills are user-defined knowledge modules that provide specialized context and instructions. Each parameter is a skill name - set to true to enable the skill, false to disable it. Enabled skills become visible to AI through the read_skill tool description and can be loaded on demand.",
    parameters: {
    },
    parametersDynamic: true,
    source: "backend/tools/skills/toggleSkills.ts",
  },
  'update_design': {
    description: "Update an existing design document (markdown) under .graycode/design/**.md. Use this when the user wants to revise the current design instead of creating a new one.",
    parameters: {
      "path": {"type":"string","description":"Target existing design document path under .graycode/design/**.md.","required":true},
      "title": {"type":"string","description":"Optional updated design title."},
      "overview": {"type":"string","description":"Optional updated one-line overview."},
      "design": {"type":"string","description":"Updated design content in markdown.","required":true},
      "changeSummary": {"type":"string","description":"Optional short summary of what changed in this design revision."},
    },
    source: "backend/tools/design/update_design.ts",
  },
  'update_plan': {
    description: "Update an existing plan document (markdown) under .graycode/plans/**.md. Use revision mode to revise the plan itself, or progress_sync mode to sync the latest TODO snapshot during implementation. In progress_sync mode, only send path, todos, updateMode, and optional changeSummary. If sourceArtifact is accidentally included, it will be ignored with a warning. Do NOT forward continuation/source-artifact carry-over fields such as sourceArtifactType, sourcePath, sourceContent, planPath, planContent, continuationPrompt, planExecutionPrompt, continuationApproved, or continuationIntent.",
    parameters: {
      "path": {"type":"string","description":"Target existing plan document path under .graycode/plans/**.md. Reuse the approved plan path here; do not send separate sourcePath or planPath fields.","required":true},
      "title": {"type":"string","description":"Optional updated plan title."},
      "overview": {"type":"string","description":"Optional updated one-line overview."},
      "plan": {"type":"string","description":"Updated plan content in markdown. Required in revision mode."},
      "todos": {"type":"array","description":"Updated TODO checklist for the plan.","items":{"type":"object"},"required":true},
      "updateMode": {"type":"string","description":"revision rewrites the plan and requires re-confirmation. progress_sync only updates TODO state during implementation. In progress_sync mode, only send path, todos, updateMode, and optional changeSummary. If sourceArtifact is included by mistake, it will be ignored with a warning.","enum":["revision","progress_sync"]},
      "sourceArtifact": {"type":"object","description":"Optional source artifact to rebind the plan to the latest confirmed design or review. Allowed only in revision mode. Use this nested object only when the schema explicitly allows it. Do NOT send sibling carry-over fields such as sourceArtifactType, sourcePath, or sourceContent."},
      "changeSummary": {"type":"string","description":"Optional short summary of what changed in this plan revision."},
    },
    source: "backend/tools/plan/update_plan.ts",
  },
  'update_progress': {
    description: "Update the project progress document at .graycode/progress.md. This refreshes summary fields, artifacts, TODO snapshot, risks, and recent log entries while returning a lightweight progress snapshot.",
    parameters: {
      "path": {"type":"string","description":"Optional target path. Must be .graycode/progress.md (or multi-root: workspace/.graycode/progress.md)."},
      "status": {"type":"string","enum":["active","blocked","completed","archived"]},
      "phase": {"type":"string","enum":["design","plan","implementation","review","maintenance"]},
      "currentFocus": {"type":"string"},
      "latestConclusion": {"type":"string"},
      "currentBlocker": {"type":"string"},
      "nextAction": {"type":"string"},
      "activeArtifacts": {"type":"object"},
      "todos": {"type":"array","items":{"type":"object"}},
      "risks": {"type":"array","items":{"type":"object"}},
      "appendLog": {"type":"array","items":{"type":"object"}},
    },
    source: "backend/tools/progress/update_progress.ts",
  },
  'validate_progress_document': {
    description: "Validate the fixed progress document at .graycode/progress.md without modifying it. Reports metadata health, section ordering, and basic invariants.",
    parameters: {
      "path": {"type":"string","description":"Target progress document path. Must be .graycode/progress.md (or multi-root: workspace/.graycode/progress.md).","required":true},
    },
    source: "backend/tools/progress/validate_progress_document.ts",
  },
  'validate_review_document': {
    description: "Validate an existing review document under .graycode/review/**.md without modifying it. Reports format, metadata health, and invariant issues.",
    parameters: {
      "path": {"type":"string","description":"Target review document path under .graycode/review/**.md","required":true},
    },
    source: "backend/tools/review/validate_review_document.ts",
  },
  'write_file': {
    descriptionDynamic: true,
    parameters: {
      "path": {"type":"string","required":true},
      "content": {"type":"string","required":true},
    },
    parametersDynamic: true,
    source: "backend/tools/file/write_file.ts",
  },
};
