#!/usr/bin/env node
/**
 * i18n 同步脚本（GrayCode 前后端语言包去重）
 *
 * 背景：backend/i18n/langs 与 frontend/src/i18n/langs 各有一份独立语言包（en/ja/zh-CN），
 * 同一词条可能两边各写一遍。本脚本建立「词条内容单一来源」机制：
 *
 *   - 单一来源：backend/i18n/langs/{zh-CN,en,ja}.ts（手写，翻译文本唯一存放处）
 *   - 映射登记：scripts/i18n-shared-manifest.json（手写；frontendKey -> backendKey）
 *   - 生成物：frontend/src/i18n/langs/_shared/{zh-CN,en,ja}.ts
 *     （AUTO-GENERATED，请勿手改；前端语言包 import 该生成物引用后端译文）
 *
 * 共享词条（映射表中登记的前端 key）在前端语言包中不再手写译文，
 * 而是通过 _shared 生成物引用 backend 语言包，翻译文本只保留一份。
 *
 * 用法：
 *   node scripts/i18n-sync.mjs            生成 _shared 语言包（幂等，重复运行结果一致）
 *   node scripts/i18n-sync.mjs --check    校验生成物与源一致（防漂移；供 CI / jest 测试调用）
 *   node scripts/i18n-sync.mjs --report   输出两端语言包盘点报告（结构 / 重复词条 / 单端词条）
 *   node scripts/i18n-sync.mjs --help     帮助
 */

import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const BACKEND_LANGS_DIR = path.join(ROOT, 'backend', 'i18n', 'langs');
const FRONTEND_LANGS_DIR = path.join(ROOT, 'frontend', 'src', 'i18n', 'langs');
const SHARED_DIR = path.join(FRONTEND_LANGS_DIR, '_shared');
const MANIFEST_PATH = path.join(ROOT, 'scripts', 'i18n-shared-manifest.json');

const LANGS = ['zh-CN', 'en', 'ja'];
/** 生成物中 backend 语言包 import 的变量名 */
const LANG_VAR = { 'zh-CN': 'backendZhCN', en: 'backendEn', ja: 'backendJa' };
/** 前端语言包 import 生成物时使用的变量名（供 --check 沙箱注入） */
const SHARED_VAR = { 'zh-CN': 'sharedZhCN', en: 'sharedEn', ja: 'sharedJa' };
/** 生成物文件 → backend 语言包的相对路径（frontend/src/i18n/langs/_shared/ → 仓库根） */
const BACKEND_IMPORT_REL = '../../../../../backend/i18n/langs';

const GENERATED_HEADER = `/**
 * AUTO-GENERATED by scripts/i18n-sync.mjs — 请勿手改！
 *
 * 共享词条生成物（单一来源：backend/i18n/langs/{zh-CN,en,ja}.ts + scripts/i18n-shared-manifest.json）。
 * 修改译文请改 backend 语言包；登记/调整共享映射请改 manifest，然后运行：
 *   node scripts/i18n-sync.mjs
 */`;

/* ------------------------------------------------------------------ */
/* 语言包解析：TS 语言包是纯数据对象（基准包无类型标注），可用沙箱求值  */
/* ------------------------------------------------------------------ */

/**
 * 读取并求值一个语言包 TS 文件，返回其中的对象字面量。
 * @param {string} filePath
 * @param {Record<string, unknown>} context 沙箱上下文（解析前端包时注入 _shared 生成物等）
 */
function loadPack(filePath, context = {}) {
    let src = fs.readFileSync(filePath, 'utf8');
    src = src.replace(/^\/\*[\s\S]*?\*\//, '');                      // 头部块注释
    src = src.replace(/^import[^\n]*\n?/gm, '');                      // import 行（含 type import）
    src = src.replace(/export\s+default\s+[\w$]+\s*;?/, '');          // export default xxx;
    src = src.replace(/^const\s+[\w$]+\s*(:\s*[^=]+?)?\s*=\s*/m, ''); // const xxx[: Type] = ...
    src = src.replace(/;\s*$/, '');
    return vm.runInNewContext(`(${src})`, context, { timeout: 10000 });
}

/**
 * 递归收集叶子 key（点分路径 -> 文案字符串），与 backend/__tests__/i18n/languageParity.test.ts 一致。
 * @param {Record<string, unknown>} tree
 * @param {string} prefix
 * @param {Map<string, string>} out
 */
function collectLeaves(tree, prefix = '', out = new Map()) {
    for (const [key, value] of Object.entries(tree)) {
        const path = prefix ? `${prefix}.${key}` : key;
        if (typeof value === 'string') {
            out.set(path, value);
        } else if (value && typeof value === 'object' && !Array.isArray(value)) {
            collectLeaves(value, path, out);
        } else {
            out.set(path, JSON.stringify(value));
        }
    }
    return out;
}

/** 归一化：折叠空白，用于"仅空白差异"的相似词条检测 */
function normalizeText(text) {
    return text.replace(/\s+/g, ' ').trim();
}

/* ------------------------------------------------------------------ */
/* Manifest                                                             */
/* ------------------------------------------------------------------ */

function loadManifest() {
    if (!fs.existsSync(MANIFEST_PATH)) {
        return { version: 1, mappings: [] };
    }
    return JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf8'));
}

/**
 * 校验 manifest 映射：backend key 必须存在于三份 backend 语言包，frontend key 格式合法。
 * @returns {string[]} 错误列表（为空即通过）
 */
function validateMappings(manifest, backendLeaves) {
    const errors = [];
    for (const [i, m] of manifest.mappings.entries()) {
        if (!m || typeof m.frontend !== 'string' || typeof m.backend !== 'string') {
            errors.push(`mappings[${i}] 缺少 frontend/backend 字段`);
            continue;
        }
        if (!/^[a-zA-Z][\w$]*(\.[a-zA-Z][\w$]*)+$/.test(m.frontend)) {
            errors.push(`mappings[${i}] frontend key 格式非法: ${m.frontend}`);
        }
        for (const lang of LANGS) {
            if (!backendLeaves[lang].has(m.backend)) {
                errors.push(`mappings[${i}] backend key 不存在（${lang}）: ${m.backend}`);
            }
        }
    }
    return errors;
}

/* ------------------------------------------------------------------ */
/* 生成                                                                 */
/* ------------------------------------------------------------------ */

/**
 * 渲染单个语言的 _shared 生成物内容（确定性：key 按字典序输出）。
 * @param {Array<{frontend: string, backend: string}>} mappings
 * @param {string} lang
 */
function renderSharedTree(mappings, lang) {
    const lines = [];
    lines.push(GENERATED_HEADER);
    lines.push('');
    lines.push(`import ${LANG_VAR[lang]} from '${BACKEND_IMPORT_REL}/${lang}';`);
    lines.push('');
    lines.push(`const ${SHARED_VAR[lang]} = {`);
    if (mappings.length === 0) {
        lines.push('    // （暂无共享词条映射）');
    } else {
        // 先按 frontend key 排序，再构建嵌套树，保证输出确定（幂等）
        const tree = {};
        for (const m of [...mappings].sort((a, b) => a.frontend.localeCompare(b.frontend))) {
            const segs = m.frontend.split('.');
            let node = tree;
            for (const s of segs.slice(0, -1)) {
                if (!node[s]) node[s] = {};
                node = node[s];
            }
            node[segs[segs.length - 1]] = m.backend;
        }
        renderNode(lines, tree, 1, lang);
    }
    lines.push('};');
    lines.push('');
    lines.push(`export default ${SHARED_VAR[lang]};`);
    lines.push('');
    return lines.join('\n');
}

/** 递归渲染嵌套树节点；叶子值为 backend 点分路径，渲染为 backend 变量属性引用 */
function renderNode(lines, node, indent, lang) {
    const pad = '    '.repeat(indent);
    for (const key of Object.keys(node).sort()) {
        const value = node[key];
        if (typeof value === 'string') {
            lines.push(`${pad}${key}: ${LANG_VAR[lang]}.${value},`);
        } else {
            lines.push(`${pad}${key}: {`);
            renderNode(lines, value, indent + 1, lang);
            lines.push(`${pad}},`);
        }
    }
}

/** 生成 _shared 语言包（幂等） */
function generate() {
    const manifest = loadManifest();
    const backend = loadBackendPacks();
    const backendLeaves = {};
    for (const lang of LANGS) backendLeaves[lang] = collectLeaves(backend[lang]);

    const errors = validateMappings(manifest, backendLeaves);
    if (errors.length > 0) {
        console.error(`[i18n-sync] manifest 校验失败（${errors.length} 处）：`);
        for (const e of errors) console.error(`  - ${e}`);
        process.exit(1);
    }

    fs.mkdirSync(SHARED_DIR, { recursive: true });
    for (const lang of LANGS) {
        const content = renderSharedTree(manifest.mappings, lang);
        fs.writeFileSync(path.join(SHARED_DIR, `${lang}.ts`), content);
    }
    console.log(
        `[i18n-sync] 生成完成: frontend/src/i18n/langs/_shared/{${LANGS.join(',')}}.ts` +
        `（${manifest.mappings.length} 条共享映射，来源 backend/i18n/langs）`
    );
}

/* ------------------------------------------------------------------ */
/* --check：防漂移校验                                                  */
/* ------------------------------------------------------------------ */

function check() {
    const manifest = loadManifest();
    const backend = loadBackendPacks();
    const backendLeaves = {};
    for (const lang of LANGS) backendLeaves[lang] = collectLeaves(backend[lang]);

    const errors = validateMappings(manifest, backendLeaves);
    if (errors.length > 0) {
        console.error(`[i18n-sync --check] manifest 校验失败（${errors.length} 处）：`);
        for (const e of errors) console.error(`  - ${e}`);
        process.exit(1);
    }

    let failed = false;

    // 1) 生成物与重新生成结果逐字节一致（防手改 / 防漏跑脚本）
    for (const lang of LANGS) {
        const filePath = path.join(SHARED_DIR, `${lang}.ts`);
        const expected = renderSharedTree(manifest.mappings, lang);
        if (!fs.existsSync(filePath)) {
            console.error(`[i18n-sync --check] 缺少生成物: ${filePath}`);
            failed = true;
        } else if (fs.readFileSync(filePath, 'utf8') !== expected) {
            console.error(`[i18n-sync --check] 生成物与源不一致（漂移）: ${filePath}`);
            console.error('  请运行 node scripts/i18n-sync.mjs 重新生成');
            failed = true;
        }
    }

    // 2) 映射运行时一致性：前端语言包（含 _shared 引用）解析出的值 === backend 源值（三语言）
    const shared = {};
    for (const lang of LANGS) {
        shared[lang] = loadPack(path.join(SHARED_DIR, `${lang}.ts`), { [LANG_VAR[lang]]: backend[lang] });
    }
    const frontend = {};
    for (const lang of LANGS) {
        frontend[lang] = loadPack(path.join(FRONTEND_LANGS_DIR, `${lang}.ts`), {
            [SHARED_VAR[lang]]: shared[lang],
        });
    }
    const feLeaves = {};
    for (const lang of LANGS) feLeaves[lang] = collectLeaves(frontend[lang]);

    for (const m of manifest.mappings) {
        for (const lang of LANGS) {
            const fe = feLeaves[lang].get(m.frontend);
            const be = backendLeaves[lang].get(m.backend);
            if (fe === undefined) {
                console.error(`[i18n-sync --check] 前端语言包缺少映射 key: ${m.frontend}（${lang}）`);
                failed = true;
            } else if (fe !== be) {
                console.error(
                    `[i18n-sync --check] 值不一致 ${m.frontend}（${lang}）: 前端 "${fe}" vs 后端 "${be}"`
                );
                failed = true;
            }
        }
    }

    if (failed) {
        console.error('[i18n-sync --check] 失败：存在漂移或映射不一致');
        process.exit(1);
    }
    console.log(
        `[i18n-sync --check] OK：${manifest.mappings.length} 条共享映射 × ${LANGS.length} 语言一致，生成物无漂移`
    );
}

/* ------------------------------------------------------------------ */
/* --report：盘点两端语言包                                              */
/* ------------------------------------------------------------------ */

function loadBackendPacks() {
    const backend = {};
    for (const lang of LANGS) backend[lang] = loadPack(path.join(BACKEND_LANGS_DIR, `${lang}.ts`));
    return backend;
}

function report() {
    const backend = loadBackendPacks();
    // 前端语言包已通过 _shared 生成物引用 backend 译文，解析前先加载生成物并注入沙箱
    const shared = {};
    for (const lang of LANGS) {
        shared[lang] = loadPack(path.join(SHARED_DIR, `${lang}.ts`), { [LANG_VAR[lang]]: backend[lang] });
    }
    const frontend = {};
    for (const lang of LANGS) {
        frontend[lang] = loadPack(path.join(FRONTEND_LANGS_DIR, `${lang}.ts`), {
            [SHARED_VAR[lang]]: shared[lang],
        });
    }

    const beLeaves = {};
    const feLeaves = {};
    for (const lang of LANGS) {
        beLeaves[lang] = collectLeaves(backend[lang]);
        feLeaves[lang] = collectLeaves(frontend[lang]);
    }

    const line = '='.repeat(72);
    console.log(line);
    console.log('LimCode i18n 语言包盘点报告');
    console.log(line);

    /* ---- 1. 结构概览 ---- */
    console.log('\n【1】结构概览（叶子 key 数）');
    for (const [side, packs, leaves] of [
        ['backend', backend, beLeaves],
        ['frontend', frontend, feLeaves],
    ]) {
        console.log(`\n  ${side}（zh-CN / en / ja 叶子数: ${leaves['zh-CN'].size} / ${leaves.en.size} / ${leaves.ja.size}）`);
        for (const [domain, value] of Object.entries(packs['zh-CN'])) {
            const count = collectLeaves(value).size;
            console.log(`    - ${domain}: ${count}`);
        }
    }

    /* ---- 2. 完全重复（按 zh 译文精确匹配） ---- */
    const manifestFrontendKeys = new Set(loadManifest().mappings.map((m) => m.frontend));
    const beZhByValue = buildValueMap(beLeaves['zh-CN']);
    const feZhByValue = buildValueMap(feLeaves['zh-CN']);
    const exactCommon = [...beZhByValue.keys()].filter((v) => feZhByValue.has(v)).sort();

    console.log('\n【2】完全重复词条（zh 译文精确相同；key 不同，值相同）');
    console.log(`  共 ${exactCommon.length} 条 zh 译文在两端同时出现（已迁移 = 该译文对应的全部 frontend key 已登记到 manifest）`);
    for (const v of exactCommon) {
        const bk = [...beZhByValue.get(v)].sort().join(', ');
        const fkList = [...feZhByValue.get(v)].sort();
        const fk = fkList.join(', ');
        const migrated = fkList.every((k) => manifestFrontendKeys.has(k)) ? '（已迁移）' : '';
        console.log(`  - "${v}" ${migrated}`);
        console.log(`      backend : ${bk}`);
        console.log(`      frontend: ${fk}`);
    }


    /* ---- 3. 三语言完全一致（zh/en/ja 译文均相同） ---- */
    const beTriple = buildTripleMap(beLeaves);
    const feTriple = buildTripleMap(feLeaves);
    const commonTriples = [...beTriple.keys()].filter((t) => feTriple.has(t)).sort();

    console.log('\n【3】三语言完全一致词条（zh/en/ja 译文在两端完全相同）——最强重复信号');
    console.log(`  共 ${commonTriples.length} 组`);
    for (const t of commonTriples) {
        const [zh, en, ja] = t.split('\u0001');
        const bk = [...beTriple.get(t)].sort().join(', ');
        const fkList = [...feTriple.get(t)].sort();
        const fk = fkList.join(', ');
        const migrated = fkList.every((k) => manifestFrontendKeys.has(k)) ? '（已迁移）' : '';
        console.log(`  - zh="${zh}" en="${en}" ja="${ja}" ${migrated}`);
        console.log(`      backend : ${bk}`);
        console.log(`      frontend: ${fk}`);
    }


    /* ---- 4. 仅空白差异的相似词条 ---- */
    const beNorm = new Map();
    for (const [v, keys] of beZhByValue) beNorm.set(normalizeText(v), keys);
    const feNorm = new Map();
    for (const [v, keys] of feZhByValue) feNorm.set(normalizeText(v), keys);
    const nearCommon = [...beNorm.keys()].filter((n) => feNorm.has(n) && !beZhByValue.has(beNorm.get(n).values().next().value));
    // 更准确：排除已在【2】中精确匹配的值
    const exactSet = new Set(exactCommon);
    const nearPairs = [];
    for (const n of beNorm.keys()) {
        if (!feNorm.has(n)) continue;
        const beVals = [...beNorm.get(n)];
        const feVals = [...feNorm.get(n)];
        for (const bv of beVals) {
            if (exactSet.has(bv)) continue;
            for (const fv of feVals) {
                if (exactSet.has(fv)) continue;
                nearPairs.push([bv, fv]);
            }
        }
    }
    console.log('\n【4】仅空白差异的相似词条（归一化后相同，原文不同）');
    console.log(`  共 ${nearPairs.length} 对`);
    for (const [bv, fv] of nearPairs) {
        console.log(`  - backend "${bv}"`);
        console.log(`    frontend "${fv}"`);
    }


    /* ---- 5. 只有一端有的词条 ---- */
    const onlyBackend = [...beZhByValue.keys()].filter((v) => !feZhByValue.has(v));
    const onlyFrontend = [...feZhByValue.keys()].filter((v) => !beZhByValue.has(v));
    console.log('\n【5】只有一端有的词条（按 zh 译文统计）');
    console.log(`  backend 独有: ${onlyBackend.length} 条（frontend 无同译文）`);
    for (const v of onlyBackend.slice(0, 15)) {
        console.log(`    - "${v}" <- ${[...beZhByValue.get(v)].sort().join(', ')}`);
    }
    if (onlyBackend.length > 15) console.log(`    ...（其余 ${onlyBackend.length - 15} 条略）`);
    console.log(`  frontend 独有: ${onlyFrontend.length} 条（backend 无同译文）`);
    for (const v of onlyFrontend.slice(0, 15)) {
        console.log(`    - "${v}" <- ${[...feZhByValue.get(v)].sort().join(', ')}`);
    }
    if (onlyFrontend.length > 15) console.log(`    ...（其余 ${onlyFrontend.length - 15} 条略）`);

    /* ---- 6. manifest 当前状态 ---- */
    const manifest = loadManifest();
    console.log('\n【6】共享映射 manifest 当前状态');
    console.log(`  已登记映射: ${manifest.mappings.length} 条（${MANIFEST_PATH}）`);
    for (const m of manifest.mappings) {
        console.log(`    - ${m.frontend} <- ${m.backend}`);
    }
    console.log('');
}

/** 值 -> key 集合（仅字符串叶子） */
function buildValueMap(leaves) {
    const map = new Map();
    for (const [k, v] of leaves) {
        if (typeof v !== 'string') continue;
        if (!map.has(v)) map.set(v, new Set());
        map.get(v).add(k);
    }
    return map;
}

/** 三语言译文三元组 -> key 集合 */
function buildTripleMap(leaves) {
    const map = new Map();
    const keys = leaves['zh-CN'].keys();
    for (const k of keys) {
        const zh = leaves['zh-CN'].get(k);
        const en = leaves.en.get(k);
        const ja = leaves.ja.get(k);
        if (typeof zh !== 'string' || typeof en !== 'string' || typeof ja !== 'string') continue;
        const triple = `${zh}\u0001${en}\u0001${ja}`;
        if (!map.has(triple)) map.set(triple, new Set());
        map.get(triple).add(k);
    }
    return map;
}

/* ------------------------------------------------------------------ */
/* CLI                                                                  */
/* ------------------------------------------------------------------ */

const args = process.argv.slice(2);
if (args.includes('--help') || args.includes('-h')) {
    console.log(
        '用法：\n' +
        '  node scripts/i18n-sync.mjs            生成 _shared 语言包（幂等）\n' +
        '  node scripts/i18n-sync.mjs --check    校验生成物与源一致（防漂移）\n' +
        '  node scripts/i18n-sync.mjs --report   输出两端语言包盘点报告\n'
    );
    process.exit(0);
}

if (args.includes('--check')) {
    check();
} else if (args.includes('--report')) {
    report();
} else {
    generate();
}

