/**
 * 跨端 parity：前端工具元数据镜像（frontend/src/utils/tools/__generated__/toolMeta.ts）
 * 与后端工具声明（backend/tools 各工具文件的 ToolDeclaration）保持一致。
 *
 * 同步机制：
 *   - 单一来源：backend/tools 下各工具文件中的 ToolDeclaration 对象字面量
 *   - 生成脚本：scripts/generate-tool-meta.mjs（静态提取「可确定」的 description/参数摘要，
 *     动态构造部分标记 descriptionDynamic/parametersDynamic）
 *   - 生成物：frontend/src/utils/tools/__generated__/toolMeta.ts（AUTO-GENERATED，勿手改）
 *
 * 防漂移手段：
 *   1. 本测试以 child_process 跑 `node scripts/generate-tool-meta.mjs --check`：
 *      脚本现场重生成并对比生成物（忽略 Git checkout 造成的物理行尾差异）——
 *      任何人手改生成物、或后端声明改动后忘记重新生成，都会在这里失败。
 *   2. 结构断言：生成物含 AUTO-GENERATED 头与类型定义。
 *   3. 覆盖断言：前端每个镜像工具（registerTool('name')）都必须在生成物中有登记，
 *      例外仅限显式 legacy 名单（如前端独有的 toggle_skills）。
 */

import { execFileSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';

const ROOT = path.resolve(__dirname, '..', '..', '..');
const SCRIPT = path.join(ROOT, 'scripts', 'generate-tool-meta.mjs');
const GENERATED_FILE = path.join(
    ROOT,
    'frontend',
    'src',
    'utils',
    'tools',
    '__generated__',
    'toolMeta.ts'
);
const FRONTEND_TOOLS_DIR = path.join(ROOT, 'frontend', 'src', 'utils', 'tools');

/** 前端独有、后端无对应声明的工具（legacy 兼容，允许不在生成物中） */
const LEGACY_FRONTEND_ONLY_TOOLS = new Set(['toggle_skills']);

/** 收集前端镜像文件中 registerTool('name', ...) 的工具名（排除 mcp/、生成物、测试、非注册文件） */
function collectFrontendMirrorToolNames(): string[] {
    const names: string[] = [];
    const walk = (dir: string): void => {
        for (const name of fs.readdirSync(dir)) {
            if (name === 'mcp' || name === '__generated__' || name === '__tests__') continue;
            const full = path.join(dir, name);
            const stat = fs.statSync(full);
            if (stat.isDirectory()) {
                walk(full);
                continue;
            }
            if (!name.endsWith('.ts')) continue;
            if (name === 'index.ts' || name === 'diffPreviewAction.ts' || name === 'toolMetaLookup.ts') continue;
            const src = fs.readFileSync(full, 'utf8');
            const re = /registerTool\(\s*'([^']+)'/g;
            let m;
            while ((m = re.exec(src)) !== null) {
                names.push(m[1]);
            }
        }
    };
    walk(FRONTEND_TOOLS_DIR);
    return [...new Set(names)];
}

function runCheck(): string {
    return execFileSync(process.execPath, [SCRIPT, '--check'], {
        cwd: ROOT,
        encoding: 'utf8',
        stdio: 'pipe',
    });
}

describe('跨端 parity：工具元数据镜像（toolMeta.ts vs backend/tools 声明）', () => {
    test('生成物与后端声明一致（scripts/generate-tool-meta.mjs --check 通过）', () => {
        // 不一致时脚本打印首个差异行并抛错（退出码非 0），execFileSync 会抛异常
        expect(() => runCheck()).not.toThrow();
    });

    test('生成物包含 AUTO-GENERATED 头、类型定义与数据导出', () => {
        const content = fs.readFileSync(GENERATED_FILE, 'utf8');
        expect(content).toContain('AUTO-GENERATED by scripts/generate-tool-meta.mjs');
        expect(content).toContain('export interface ToolMeta');
        expect(content).toContain('export const toolMeta: Record<string, ToolMeta>');
    });

    test('生成物工具名集合非空且覆盖核心工具', () => {
        const content = fs.readFileSync(GENERATED_FILE, 'utf8');
        for (const tool of ['read_file', 'write_file', 'execute_command', 'get_activity_stats', 'create_design', 'todo_write']) {
            expect(content).toContain(`'${tool}':`);
        }
    });

    test('每个前端镜像工具都在生成物中有登记（legacy 名单除外）', () => {
        const content = fs.readFileSync(GENERATED_FILE, 'utf8');
        const mirrorNames = collectFrontendMirrorToolNames();
        expect(mirrorNames.length).toBeGreaterThan(30);
        for (const name of mirrorNames) {
            if (LEGACY_FRONTEND_ONLY_TOOLS.has(name)) continue;
            expect(content).toContain(`'${name}':`);
        }
    });

    test('关键工具元数据样例：静态描述与动态标记符合预期', () => {
        const content = fs.readFileSync(GENERATED_FILE, 'utf8');
        // 静态可提取的工具应带 description
        const staticBlock = content.match(/  'create_design': \{[\s\S]*?\n  \},/);
        expect(staticBlock).not.toBeNull();
        expect(staticBlock![0]).toContain('description:');
        // 动态构造的工具（execute_command 依赖运行时 OS/Shell 环境）应标记 descriptionDynamic
        const dynamicBlock = content.match(/  'execute_command': \{[\s\S]*?\n  \},/);
        expect(dynamicBlock).not.toBeNull();
        expect(dynamicBlock![0]).toContain('descriptionDynamic: true');
    });
});
